### PR TITLE
fix chat list double scrollbar

### LINKED ISSUE #3252: Chat list scrollbar UI regression
On dev
image
While on prod
image
Maybe related https://github.com/LAION-AI/Open-Assistant/pull/3201

### PR DESCRIPTION
**Pull request by notmd**
close #3252
- Dont render scrollbar in /chat page anymore.
- Fix an overflow bug in the chat list

I have manually verified all the UI

### CODE REVIEW

File: website/src/components/Chat/ChatListItem.tsx [hunk 1]
```diff
@@ -306,7 +306,8 @@ const ChatListItemIconButton = ({ label, onClick, icon }: ChatListItemIconButton
   return (
     <Tooltip label={label}>
       <Box
-        as="button"
+        as="div"
+        role="button"
```
Comment (notmd) [inline website/src/components/Chat/ChatListItem.tsx:310]: Fix this bug 
`validateDOMNesting(...): <button> cannot appear as a descendant of <button>.`

**Review by AbdBarho — APPROVED** [review]
Thanks!
