### PR TITLE
System config parameter view

### LINKED ISSUE #1068: Add minimalistic system config parameter view (readonly, just the json) to admin dashboard
- use backend API: GET `/api/v1/admin/backend_settings/full` and if that fails use GET `/api/v1/admin/backend_settings/public` as a fallback (only trusted api-clients can access the full settings).
- add a "Parameters" tab on the left side, if selected show simply the current config as JSON text (similar to other things in the admin interface).

### PR DESCRIPTION
**Pull request by notmd**
close #1068 

- Add new AdminArea component
- Add new json variant to Card component

image

### CODE REVIEW

File: website/src/components/AdminArea.tsx [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+  useEffect(() => {
+    if (status === "loading") {
+      return;
+    }
+    if (session?.user.role === "admin") {
+      return;
+    }
+    router.push("/");
+  }, [router, session, status]);
```
Comment (AbdBarho) [inline website/src/components/AdminArea.tsx:17]: this use effect can be simplified into 
```ts
if (session?.user.role !== "admin")
   router.push("/")
```

**Review by AbdBarho — COMMENTED** [review]
looks good

File: website/src/components/AdminArea.tsx (hunk 1 above)
Comment (notmd) [reply website/src/components/AdminArea.tsx:17]: > this use effect can be simplified into
> 
> ```ts
> if (session?.user.role !== "admin")
>    router.push("/")
> ```

This will rediect if session is null (when the status is loading or unauthenticated)
image

Comment (AbdBarho) [reply website/src/components/AdminArea.tsx:17]: oh I see! makes sense

**Review by AbdBarho — APPROVED** [review]
