### PR TITLE
Fix numbered list alignment

### LINKED ISSUE #1818: The Markdown numbering system does not display correctly when more than one digit is used.
image

### PR DESCRIPTION
**Pull request by Slowlife01**
Fixes #1818

image

### CODE REVIEW

File: website/src/components/Messages/RenderedMarkdown.tsx [hunk 1]
```diff
@@ -70,6 +70,9 @@ const sx: SystemStyleObject = {
       borderBottomColor: "gray.700",
     },
   },
+  "ol li::marker": {
+    content: "counter(list-item) '.'",
+  },
```
Comment (AbdBarho) [inline website/src/components/Messages/RenderedMarkdown.tsx:75]: could you please explain this fix to me?

**Review by notmd — APPROVED** [review]
Wow thank a lot, first time I see this magic

File: website/src/components/Messages/RenderedMarkdown.tsx (hunk 1 above)
Comment (notmd) [reply website/src/components/Messages/RenderedMarkdown.tsx:75]: Whoop sorry, I didn't see your comment. Here is more information about this https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters
