### PR TITLE
fix message overflow

### LINKED ISSUE #1698: Dots menu popup created inside owning element
In today's deployment, the pop-up dots menu is kinda borked, breaks the text, isn't usable with short messages:

https://user-images.githubusercontent.com/273059/219822141-00b46f41-242d-43c9-8d6b-b99de12eca41.mp4

### PR DESCRIPTION
**Pull request by notmd**
Fix #1698, also support rtl for MessageTableEntry component
before
image
after
image

### CODE REVIEW

File: website/src/components/Messages/MessageTableEntry.tsx [hunk 1]
```diff
@@ -111,27 +107,28 @@ export function MessageTableEntry({ message, enabled, highlight, showAuthorBadge
   const { t } = useTranslation(["message"]);
 
   return (
-    <HStack w={["full", "full", "full", "fit-content"]} gap={0.5} alignItems="start">
+    <HStack w={["full", "full", "full", "fit-content"]} gap={0.5} alignItems="start" maxW="full" position="relative">
```
Comment (notmd) [inline website/src/components/Messages/MessageTableEntry.tsx:110]: Have to move position relative to this element to fix         
image
Not sure why adding overflow-x: auto makes the badge hidden.

File: website/src/components/Messages/MessageTableEntry.tsx [hunk 2]
```diff
@@ -267,61 +271,63 @@ const MessageActions = ({
...
-          {t("label_action")}
-        </MenuItem>
-        <MenuItem onClick={onReport} icon={<Flag />}>
-          {t("report_action")}
-        </MenuItem>
-        <MenuDivider />
-        <MenuItem as={NextLink} href={`/messages/${id}`} target="_blank" icon={<MessageSquare />}>
-          {t("open_new_tab_action")}
-        </MenuItem>
+      <Portal>
```
Comment (notmd) [inline website/src/components/Messages/MessageTableEntry.tsx:274]: Portal is required here. Having the menu inside the component will make the parent overflow. Even when adding over-flow: auto it still has an ugly scroll bar

**Review by rjmacarthy — APPROVED** [review]

**Review by AbdBarho — APPROVED** [review]
Thanks
